web:
    image: nginx:latest
    ports:
        - "50080:80"
    expose:
        - "80"
    volumes:
        - ./src:/src:ro
        - ./site.conf:/etc/nginx/conf.d/default.conf:ro
    links:
        - php
php:
    image: php:7-fpm
    volumes:
        - ./src:/src:ro
